package com.app.yjw.util;

public enum ErrorCode {
	E_SUCCESS,
	/**此错误仅限调试使用*/E_FAILED,
	E_LOGIN_FAILED,
	E_DUBLICATE_ID,
	E_DUBLICATE_NAME,
	E_FAIL_TO_GET_VALIDATE_INFO,	
	E_INVALIDATE_FAILED,
	E_CONNECTION_ERROR,
	E_SET_CHAT_FAILED,
	E_NULL_MSG,
	E_NULL_DEAL, 
	E_ADD_DEAL_FAILED, 
	E_DEL_DEAL_FAILED, 
	E_NULL_TRANS, 
	E_ADD_TRANS_FAILED, 
	E_DEL_TRANS_FAILED, 
	E_CONF_TRANS_ERROR,
	E_NOT_ENOUGH_BALANCE, 
	E_SYNC_USER_FAILED, 
}
